name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  WASM_PATH: wasm-src
  E2E_PATH: tests/e2e

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            - recursive: false
      - run: pnpm lint

  format-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            - recursive: false
      - run: pnpm format:check

  lint-wasm:
    name: Lint WASM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WASM_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy -- -D warnings

  format-check-wasm:
    name: Format check WASM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WASM_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check

  test:
    name: Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [lint, format-check, lint-wasm, format-check-wasm]
    defaults:
      run:
        working-directory: ${{ env.E2E_PATH }}
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            - recursive: false
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ${{ env.E2E_PATH }}/playwright-report/
          retention-days: 30
