name: Lint and format check

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - run: pnpm lint

  format-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - run: pnpm format:check
