name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  E2E_PATH: tests/e2e
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install library dependencies
        run: pnpm install
      - name: Build library
        run: pnpm build
      - name: Install E2E test dependencies
        run: pnpm install
        working-directory: ${{ env.E2E_PATH }}
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: ${{ env.E2E_PATH }}
      - name: Run Playwright tests
        run: pnpm exec playwright test
        working-directory: ${{ env.E2E_PATH }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ${{ env.E2E_PATH }}/playwright-report/
          retention-days: 30
